{
  "project_info": {
    "project_number": "143792551988",
    "project_id": "clean-vista-305414",
    "storage_bucket": "clean-vista-305414.firebasestorage.app"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:143792551988:android:8fdbb04b2a1cdaaf7f3261",
        "android_client_info": {
          "package_name": "com.cryptodarks.telegram"
        }
      },
      "oauth_client": [
        {
          "client_id": "143792551988-t6ja9qpgs8cviko5kbal9u8fc0idmt7s.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "AIzaSyD4MjsOFAdIEqH3AmO5HMlI5zqBTomy_EM"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "143792551988-t6ja9qpgs8cviko5kbal9u8fc0idmt7s.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "1"
}
